/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author katsuro
 */
public class ahli2 extends javax.swing.JPanel {

    public ahli2() {
        initComponents();showTabel();
    }
    public ArrayList<listKeahlian> listTabelKeahlian (){
           ArrayList<listKeahlian> listTabelKeahlian = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query= "select Keahlian.IDKeahlian, Karyawan.IDKaryawan, Keahlian.NamaKeahlian, Karyawan.Nama " +
" from Keahlian, Karyawan " +
" where Keahlian.IDKeahlian=Karyawan.IDKeahlian ";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listKeahlian list;
            while(rs.next()){
                list= new listKeahlian(rs.getString("IDKeahlian"),rs.getString("IDKaryawan"),
                                       rs.getString("NamaKeahlian"),rs.getString("Nama"));
                listTabelKeahlian.add(list);
            }
         
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
        return listTabelKeahlian;
    }
    public void showTabel(){
        ArrayList<listKeahlian> list= listTabelKeahlian ();
        DefaultTableModel  model = (DefaultTableModel)tabelKeahlian1.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDKeahlian();
            row[1]=list.get(i).getIDKaryawan();
            row[2]=list.get(i).getNamaKeahlian();
            row[3]=list.get(i).getNama();
            
            model.addRow(row);
        }
        
    }
    public ArrayList<listKeahlian> listTabelKeahlian1 (){
           ArrayList<listKeahlian> listTabelKeahlian = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String dapat = cariNama.getText();
            String query= "select Keahlian.IDKeahlian, Karyawan.IDKaryawan, Keahlian.NamaKeahlian, Karyawan.Nama " +
" from Keahlian, Karyawan " +
" where Keahlian.IDKeahlian=Karyawan.IDKeahlian and Nama like "+"'"+"%"+dapat+"%"+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listKeahlian list;
            while(rs.next()){
                list= new listKeahlian(rs.getString("IDKeahlian"),rs.getString("IDKaryawan"),
                                       rs.getString("NamaKeahlian"),rs.getString("Nama"));
                listTabelKeahlian.add(list);
            }
         
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
        return listTabelKeahlian;
    }
    public void showTabel1(){
        ArrayList<listKeahlian> list= listTabelKeahlian1 ();
        DefaultTableModel  model = (DefaultTableModel)tabelKeahlian1.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDKeahlian();
            row[1]=list.get(i).getIDKaryawan();
            row[2]=list.get(i).getNamaKeahlian();
            row[3]=list.get(i).getNama();
            
            model.addRow(row);
        }
    }
    public void sc(){
        DefaultTableModel  model = (DefaultTableModel)tabelKeahlian1.getModel();
        model.setRowCount(0);
        showTabel1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKeahlian1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cariNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelKeahlian1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelKeahlian1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Keahlian", "ID Karyawan", "Nama Keahlian", "Nama Karyawan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKeahlian1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKeahlian1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKeahlian1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 760, 200));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Keahlian");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Cari Nama");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 70, 20));

        cariNama.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel2.add(cariNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 160, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelKeahlian1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKeahlian1MouseClicked

    }//GEN-LAST:event_tabelKeahlian1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel  model = (DefaultTableModel)tabelKeahlian1.getModel();
        model.setRowCount(0);
        showTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sc();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKeahlian1;
    // End of variables declaration//GEN-END:variables
}
