/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author shafira
 */
public class berpang extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public berpang() {
        initComponents();
        showTabel();
        ComboKaryawan();
        ComboPangkat();
        
    }
    public ArrayList<listBerpangkat> listTabelBerpangkat (){
           ArrayList<listBerpangkat> listTabelBerpangkat = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            String query= "select Karyawan.IDKaryawan, Karyawan.Nama, Pangkat.IDPangkat, Berpangkat.TglJabat \n" +
                           " from Karyawan, Berpangkat,Pangkat\n" +
                          "  where Karyawan.IDKaryawan=Berpangkat.IDKaryawan "
                    + "and  Pangkat.IDPangkat=Berpangkat.IDPangkat";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listBerpangkat list;
            while(rs.next()){
                list = new listBerpangkat(rs.getString("IDKaryawan"),rs.getString("Nama"),rs.getString("IDPangkat"),
                                       rs.getString("TglJabat"));
                listTabelBerpangkat.add(list);
            }
            
            
   }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    return listTabelBerpangkat;
    }
    public void showTabel(){
        ArrayList<listBerpangkat> list= listTabelBerpangkat ();
        DefaultTableModel  model = (DefaultTableModel)tabelBerpangkat.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDKaryawan();
            row[1]=list.get(i).getNamaKaryawan();
            row[2]=list.get(i).getIDPangkat();
            row[3]=list.get(i).getTanggalJabat();
            
            model.addRow(row);
        }
    }
    private void ComboPangkat(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query ="select * from Pangkat";
            PreparedStatement pst =con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("IDPangkat");
                String name=rs.getString("NamaKepangkatan");
                editComboPangkat.addItem(id);
                
            }

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    private void ComboKaryawan(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query ="select * from Karyawan";
            PreparedStatement pst =con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("IDKaryawan");
                String name=rs.getString("Nama");
                editComboKaryawan.addItem(id);
                
            }

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    private String ambilTabel(int row,int col){
        return tabelBerpangkat.getModel().getValueAt(row, col).toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBerpangkat = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        inputberpangkat = new javax.swing.JButton();
        editComboKaryawan = new javax.swing.JComboBox<>();
        editComboPangkat = new javax.swing.JComboBox<>();
        editBerpangkat = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        editTanggalJabat = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setText("Berpangkat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 180, 50));

        tabelBerpangkat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelBerpangkat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Karyawan", "Nama", "IDPangkat", "Tgl Pengangkatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelBerpangkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBerpangkatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBerpangkat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 710, 190));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("EDIT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 70, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("ID Pangkat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 80, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Tgl Pengangkatan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("ID Karyawan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 280, 80, 30));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 80, 30));

        jButton3.setBackground(new java.awt.Color(36, 47, 65));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, 80, 30));

        inputberpangkat.setBackground(new java.awt.Color(36, 47, 65));
        inputberpangkat.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        inputberpangkat.setForeground(new java.awt.Color(255, 255, 255));
        inputberpangkat.setText("INPUT");
        inputberpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputberpangkatActionPerformed(evt);
            }
        });
        jPanel1.add(inputberpangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 80, 30));

        editComboKaryawan.setEnabled(false);
        editComboKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editComboKaryawanActionPerformed(evt);
            }
        });
        jPanel1.add(editComboKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, -1));

        editComboPangkat.setEnabled(false);
        jPanel1.add(editComboPangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 120, -1));

        editBerpangkat.setBackground(new java.awt.Color(36, 47, 65));
        editBerpangkat.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        editBerpangkat.setForeground(new java.awt.Color(255, 255, 255));
        editBerpangkat.setText("EDIT");
        editBerpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBerpangkatActionPerformed(evt);
            }
        });
        jPanel1.add(editBerpangkat, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 80, 30));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));
        jPanel1.add(editTanggalJabat, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputberpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputberpangkatActionPerformed

        berpang1 s = new berpang1();
        s.setVisible(true);
    }//GEN-LAST:event_inputberpangkatActionPerformed

    private void tabelBerpangkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBerpangkatMouseClicked
        
        int angka = tabelBerpangkat.getSelectedRow();
        
        for(int i=0; i<4; i++){
            if(i==0){
                editComboKaryawan.setSelectedItem(ambilTabel(angka,i));
            }
            if(i==1){
                
            }
            if(i==2){
                editComboPangkat.setSelectedItem(ambilTabel(angka,i));
            }
            if (i==3){
                try {
                String value =tabelBerpangkat.getValueAt(angka, i).toString();
                SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
                    editTanggalJabat.setDate(date.parse(value));
                } catch (ParseException ex) {
                    
                }
            }
        }
     
    }//GEN-LAST:event_tabelBerpangkatMouseClicked

    private void editBerpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBerpangkatActionPerformed
        editComboKaryawan.setEnabled(true);
        editComboPangkat.setEnabled(true);
        editTanggalJabat.setEnabled(true);
       
    }//GEN-LAST:event_editBerpangkatActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel  model = (DefaultTableModel)tabelBerpangkat.getModel();
       model.setRowCount(0);
        showTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            int row =tabelBerpangkat.getSelectedRow();
            String value= "'"+tabelBerpangkat.getModel().getValueAt(row, 0).toString()+"'";
            String value2= "'"+tabelBerpangkat.getModel().getValueAt(row, 2).toString()+"'";
        
            String Tanggal ="'"+tabelBerpangkat.getModel().getValueAt(row, 3).toString()+"'";
            String query2 = "update Berpangkat "
                    + "set IDKaryawan=?,IDPangkat =? ,TglJabat=? w"
                    + "here IDKaryawan="
                    +value
                    +" and "+"TglJabat="+Tanggal
                    +" and "+"IDPangkat="+value2;
            
            PreparedStatement pst= con.prepareStatement(query2);
            pst.setString(1,editComboKaryawan.getSelectedItem().toString());
            pst.setString(2,editComboPangkat.getSelectedItem().toString());
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            pst.setString(3,sdf.format(editTanggalJabat.getDate()));
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated");
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            int row =tabelBerpangkat.getSelectedRow();
            String value= ( tabelBerpangkat.getModel().getValueAt(row, 0).toString());
            String vl="'"+value+"'";
            String Tanggal ="'"+tabelBerpangkat.getModel().getValueAt(row, 3).toString()+"'";
            
            String queryy="delete from Berpangkat where IDKaryawan="+vl+""
                    + " and "+"TglJabat="+Tanggal;
            
            PreparedStatement pst= con.prepareStatement(queryy);
            
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "Delete Success");
            
            
            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editComboKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editComboKaryawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editComboKaryawanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editBerpangkat;
    private javax.swing.JComboBox<String> editComboKaryawan;
    private javax.swing.JComboBox<String> editComboPangkat;
    private com.toedter.calendar.JDateChooser editTanggalJabat;
    private javax.swing.JButton inputberpangkat;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelBerpangkat;
    // End of variables declaration//GEN-END:variables
}
