/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sbd.divisi1;
/**
 *
 * @author shafira
 */
public class divisi extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public divisi() {
        initComponents();
        comboIDKaryawan();
        showTabel();
        
        
       
    }
    
    public ArrayList<listDivisi> listTabelDivisi (){
           ArrayList<listDivisi> listTabelDivisi = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            String query= "select * from Divisi";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listDivisi list;
            while(rs.next()){
                list = new listDivisi(rs.getString("IDDivisi"),rs.getString("NamaDivisi"),rs.getString("Bidang"),rs.getString("IDKaryawan"));
                listTabelDivisi.add(list);
            }
            
            
   }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    return listTabelDivisi;}
    
    public void showTabel(){
        ArrayList<listDivisi> list= listTabelDivisi ();
        DefaultTableModel  model = (DefaultTableModel)listTabelDivisi.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDDivisi();
            row[1]=list.get(i).getNamaDivisi();
            row[2]=list.get(i).getBidang();
            row[3]=list.get(i).getIDKaryawan();
            
            model.addRow(row);
        }
    }
    
    
    
    private void comboIDKaryawan(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query ="select * from Karyawan";
            PreparedStatement pst =con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            editKaryawan.addItem("");
            while(rs.next()){
                String id = rs.getString("IDKaryawan");
               
                editKaryawan.addItem(id);
                
            }

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listTabelDivisi = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editDivisi = new javax.swing.JTextField();
        editBidang = new javax.swing.JTextField();
        editNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        inputdivisi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        editKaryawan = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setText("Divisi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, -1, -1));

        listTabelDivisi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        listTabelDivisi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Divisi", "Nama", "Bidang", "ID Karyawan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listTabelDivisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTabelDivisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listTabelDivisi);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 700, 188));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("EDIT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 50, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("DIV");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("IDKaryawan");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Nama");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        editDivisi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editDivisi.setEnabled(false);
        jPanel1.add(editDivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 100, -1));

        editBidang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editBidang.setEnabled(false);
        jPanel1.add(editBidang, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, -1));

        editNama.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editNama.setEnabled(false);
        jPanel1.add(editNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 140, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REFRESH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, -1, 30));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 70, 30));

        jButton3.setBackground(new java.awt.Color(36, 47, 65));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 80, 30));

        inputdivisi.setBackground(new java.awt.Color(36, 47, 65));
        inputdivisi.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        inputdivisi.setForeground(new java.awt.Color(255, 255, 255));
        inputdivisi.setText("INPUT");
        inputdivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputdivisiActionPerformed(evt);
            }
        });
        jPanel1.add(inputdivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 70, 30));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Bidang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        jButton4.setBackground(new java.awt.Color(36, 47, 65));
        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 80, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("ID Divisi");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        editKaryawan.setEnabled(false);
        jPanel1.add(editKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 140, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputdivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputdivisiActionPerformed
        divisi1 select = new divisi1();
        select.setVisible(true);
    }//GEN-LAST:event_inputdivisiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       DefaultTableModel  model = (DefaultTableModel)listTabelDivisi.getModel();
       model.setRowCount(0);
       showTabel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listTabelDivisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTabelDivisiMouseClicked
        int angka = listTabelDivisi.getSelectedRow();
        
        for(int i=0; i<4; i++){
            if(i==0){
                StringBuilder a= new StringBuilder(ambilTabel(angka,i).toString());
                editDivisi.setText(a.delete(0, 3).toString());
            }
            else if(i==1){
                editNama.setText(ambilTabel(angka,i).toString());
            }
            else if(i==2){
                editBidang.setText(ambilTabel(angka,i).toString());
            }
            else if (i==3){
               
                  editKaryawan.setSelectedItem(ambilTabel(angka,i));
         
            }
        }
        
    }//GEN-LAST:event_listTabelDivisiMouseClicked

    private Object ambilTabel(int row,int col){
        return listTabelDivisi.getModel().getValueAt(row, col).toString();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        editDivisi.setEnabled(true);
        editNama.setEnabled(true);
        editBidang.setEnabled(true);
        editKaryawan.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
         try{
             if(editKaryawan.getSelectedIndex()==0){
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            int row =listTabelDivisi.getSelectedRow();
            String ID=listTabelDivisi.getModel().getValueAt(row, 0).toString();
            String query ="update Divisi "
                    + "set IDDivisi=?, NamaDivisi=?,Bidang=?,IDKaryawan=NULLIF('','') "
                    + "where IDDivisi="+"'"+ID+"'";
            PreparedStatement pst =con.prepareStatement(query);
            
            
            
            pst.setString(1, "DIV"+editDivisi.getText());
            pst.setString(2, editNama.getText());
            pst.setString(3, editBidang.getText());
            
            pst.executeUpdate();
                 
             }
             else if(editKaryawan.getSelectedIndex()!=0){
                 Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            int row =listTabelDivisi.getSelectedRow();
            String ID=listTabelDivisi.getModel().getValueAt(row, 0).toString();
            String query ="update Divisi "
                    + "set IDDivisi=?, NamaDivisi=?,Bidang=?,IDKaryawan=? "
                    + "where IDDivisi="+"'"+ID+"'";
            PreparedStatement pst =con.prepareStatement(query);
            
            
            
            pst.setString(1, "DIV"+editDivisi.getText());
            pst.setString(2, editNama.getText());
            pst.setString(3, editBidang.getText());
            pst.setString(4, editKaryawan.getSelectedItem().toString());
            pst.executeUpdate();
            }
             
             
            
            
            
            
            JOptionPane.showMessageDialog(null, "Updated");
            
            

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            int row =listTabelDivisi.getSelectedRow();
            String ID=listTabelDivisi.getModel().getValueAt(row, 0).toString();
            String query ="delete from Divisi where IDDivisi= "+"'"+ID+"'";
            PreparedStatement pst =con.prepareStatement(query);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Delete Succes");
            
            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField editBidang;
    private javax.swing.JTextField editDivisi;
    private javax.swing.JComboBox<String> editKaryawan;
    private javax.swing.JTextField editNama;
    private javax.swing.JButton inputdivisi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listTabelDivisi;
    // End of variables declaration//GEN-END:variables
}
