/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author katsuro
 */
public class karyawan3 extends javax.swing.JPanel {

    /**
     * Creates new form karyawan3
     */
    public karyawan3() {
        initComponents();showTabel();
    }
    public ArrayList<listKaryawan> listDataKar (){
           ArrayList<listKaryawan> listDataKar = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            String query= "select IDKaryawan, Nama, Alamat, TglLahir  from Karyawan";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listKaryawan list;
            while(rs.next()){
                list = new listKaryawan(rs.getString("IDKaryawan"),rs.getString("Nama"),rs.getString("Alamat"),rs.getString("TglLahir"));
                listDataKar.add(list);
            }
            
            
   }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    return listDataKar;
    
    }
    
    public ArrayList<listKaryawan> listDataKarS (){
           ArrayList<listKaryawan> listDataKar = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String saya = cariNama.getText();
            String query= "select IDKaryawan, Nama, Alamat, TglLahir  from Karyawan where Nama like "+"'"+"%"+saya+"%"+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listKaryawan list;
            while(rs.next()){
                list = new listKaryawan(rs.getString("IDKaryawan"),rs.getString("Nama"),rs.getString("Alamat"),rs.getString("TglLahir"));
                listDataKar.add(list);
            }
            
            
   }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    return listDataKar;
    
    }
    
    public void showTabel(){
        
        ArrayList<listKaryawan> list= listDataKar ();
        DefaultTableModel  model = (DefaultTableModel)tabelKaryawan.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDKaryawan();
            row[1]=list.get(i).getNama();
            row[2]=list.get(i).getAlamat();
            row[3]=list.get(i).getTglLahir();
            
            
            model.addRow(row);
        }
    }
    public void seacrh(){
        DefaultTableModel  model = (DefaultTableModel)tabelKaryawan.getModel();
        model.setRowCount(0);
        showS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKaryawan = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        cariNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Biodata Karyawan");

        tabelKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Karyawan", "Nama Karyawan", "Alamat", "Tgl Lahir"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelKaryawan);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Cari Nama");

        cariNama.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cariNama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2))
                    .addComponent(cariNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        seacrh();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel  model = (DefaultTableModel)tabelKaryawan.getModel();
        model.setRowCount(0);
        showTabel();
    }//GEN-LAST:event_jButton2ActionPerformed
    public void showS(){
        ArrayList<listKaryawan> list= listDataKarS ();
        DefaultTableModel  model = (DefaultTableModel)tabelKaryawan.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDKaryawan();
            row[1]=list.get(i).getNama();
            row[2]=list.get(i).getAlamat();
            row[3]=list.get(i).getTglLahir();
            
            
            model.addRow(row);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelKaryawan;
    // End of variables declaration//GEN-END:variables
}
