/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;

import paneles.CambiaPanel;

/**
 *
 * @author shafira
 */
public class menu4 extends javax.swing.JFrame {

    String bisa;
    public menu4() {
        initComponents();
        new CambiaPanel(pnlHOME, new home()); 
    }
    
    public menu4(nampung a) {
        initComponents();
        halloText.setText("Hai,"+a.getValue(0)+"!");
        bisa=a.getValue(0).toString();
        new CambiaPanel(pnlHOME, new home((String) a.getValue(0)));
    }
    private void jalan(){
        int posisi = this.pnlMenu.getX();
        if(posisi>-1) {
            Animacion.Animacion.mover_izquierda(0, -220, 2, 2, pnlMenu);
        } else {
            Animacion.Animacion.mover_derecha(-220, 0, 2, 2, pnlMenu);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        pnlMenu = new javax.swing.JPanel();
        home = new rsbuttom.RSButtonMetro();
        karyawan = new rsbuttom.RSButtonMetro();
        div = new rsbuttom.RSButtonMetro();
        ahli = new rsbuttom.RSButtonMetro();
        pang = new rsbuttom.RSButtonMetro();
        proker = new rsbuttom.RSButtonMetro();
        gaji = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        halloText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlHOME = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(803, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 60));

        pnlMenu.setBackground(new java.awt.Color(97, 212, 195));

        home.setBackground(new java.awt.Color(97, 212, 195));
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/house-24.png"))); // NOI18N
        home.setText("   HOME");
        home.setColorBorde(null);
        home.setColorHover(new java.awt.Color(36, 47, 65));
        home.setColorNormal(new java.awt.Color(97, 212, 195));
        home.setColorPressed(new java.awt.Color(153, 153, 153));
        home.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        karyawan.setBackground(new java.awt.Color(97, 212, 195));
        karyawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/group-24.png"))); // NOI18N
        karyawan.setText("   DATA KARYAWAN");
        karyawan.setColorBorde(null);
        karyawan.setColorHover(new java.awt.Color(36, 47, 65));
        karyawan.setColorNormal(new java.awt.Color(97, 212, 195));
        karyawan.setColorPressed(new java.awt.Color(153, 153, 153));
        karyawan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        karyawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                karyawanActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(97, 212, 195));
        div.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/badge-2-24.png"))); // NOI18N
        div.setText("   DIVISI");
        div.setColorBorde(null);
        div.setColorHover(new java.awt.Color(36, 47, 65));
        div.setColorNormal(new java.awt.Color(97, 212, 195));
        div.setColorPressed(new java.awt.Color(153, 153, 153));
        div.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        div.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        ahli.setBackground(new java.awt.Color(97, 212, 195));
        ahli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/computer-24.png"))); // NOI18N
        ahli.setText("   KEAHLIAN");
        ahli.setColorBorde(null);
        ahli.setColorHover(new java.awt.Color(36, 47, 65));
        ahli.setColorNormal(new java.awt.Color(97, 212, 195));
        ahli.setColorPressed(new java.awt.Color(153, 153, 153));
        ahli.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ahli.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ahli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ahliActionPerformed(evt);
            }
        });

        pang.setBackground(new java.awt.Color(97, 212, 195));
        pang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/medal-24.png"))); // NOI18N
        pang.setText("   PANGKAT");
        pang.setColorBorde(null);
        pang.setColorHover(new java.awt.Color(36, 47, 65));
        pang.setColorNormal(new java.awt.Color(97, 212, 195));
        pang.setColorPressed(new java.awt.Color(153, 153, 153));
        pang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        pang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangActionPerformed(evt);
            }
        });

        proker.setBackground(new java.awt.Color(97, 212, 195));
        proker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/combo-24.png"))); // NOI18N
        proker.setText("   PROGRAM KERJA");
        proker.setColorBorde(null);
        proker.setColorHover(new java.awt.Color(36, 47, 65));
        proker.setColorNormal(new java.awt.Color(97, 212, 195));
        proker.setColorPressed(new java.awt.Color(153, 153, 153));
        proker.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        proker.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        proker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prokerActionPerformed(evt);
            }
        });

        gaji.setBackground(new java.awt.Color(97, 212, 195));
        gaji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/cash-receiving-24.png"))); // NOI18N
        gaji.setText("   GAJI");
        gaji.setColorBorde(null);
        gaji.setColorHover(new java.awt.Color(36, 47, 65));
        gaji.setColorNormal(new java.awt.Color(97, 212, 195));
        gaji.setColorPressed(new java.awt.Color(153, 153, 153));
        gaji.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        gaji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gajiActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img1/administrator-64.png"))); // NOI18N

        halloText.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        halloText.setText("Hai, Shafira!");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
        jLabel3.setText("Keluar");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 2, 14)); // NOI18N
        jLabel4.setText("USER |");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(karyawan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(div, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ahli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proker, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gaji, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(halloText)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMenuLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(halloText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(32, 32, 32)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ahli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(proker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlMenuLayout.createSequentialGroup()
                    .addGap(100, 100, 100)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(348, Short.MAX_VALUE)))
        );

        jPanel2.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 460));

        pnlHOME.setBackground(new java.awt.Color(255, 255, 255));
        pnlHOME.setLayout(new javax.swing.BoxLayout(pnlHOME, javax.swing.BoxLayout.LINE_AXIS));
        jPanel2.add(pnlHOME, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 870, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new pang2());
    }//GEN-LAST:event_pangActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jalan();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new home());
    }//GEN-LAST:event_homeActionPerformed

    private void karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_karyawanActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new karyawan3());
    }//GEN-LAST:event_karyawanActionPerformed

    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new divisi2());
    }//GEN-LAST:event_divActionPerformed

    private void ahliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ahliActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new ahli2());
    }//GEN-LAST:event_ahliActionPerformed

    private void prokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prokerActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new pro2());
    }//GEN-LAST:event_prokerActionPerformed

    private void gajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gajiActionPerformed
        jalan();
        new CambiaPanel(pnlHOME, new Gaji2());
    }//GEN-LAST:event_gajiActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        dispose();
        sbd1 ak = new sbd1();
        ak.setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro ahli;
    private rsbuttom.RSButtonMetro div;
    private rsbuttom.RSButtonMetro gaji;
    private javax.swing.JLabel halloText;
    private rsbuttom.RSButtonMetro home;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private rsbuttom.RSButtonMetro karyawan;
    private rsbuttom.RSButtonMetro pang;
    private javax.swing.JPanel pnlHOME;
    private javax.swing.JPanel pnlMenu;
    private rsbuttom.RSButtonMetro proker;
    // End of variables declaration//GEN-END:variables
}
