/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author katsuro
 */
public class pang2 extends javax.swing.JPanel {

    /**
     * Creates new form pang2
     */
    public pang2() {
        initComponents();showTabelPangkat();
    }
    public ArrayList<listPangkat> listTabelPangkat(){
        ArrayList<listPangkat> listTabelPangkat = new ArrayList<>();
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query= "select Pangkat.IDPangkat, Pangkat.NamaKepangkatan, Karyawan.IDKaryawan, Karyawan.Nama, Pangkat.Gaji " +
                          "from Pangkat, Karyawan, Berpangkat " +
                          "where Pangkat.IDPangkat=Berpangkat.IDPangkat and Karyawan.IDKaryawan=Berpangkat.IDKaryawan";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listPangkat list;
            while(rs.next()){
                list= new listPangkat(rs.getString("IDPangkat"),rs.getString("NamaKepangkatan"),
                                       rs.getString("IDKaryawan"),rs.getString("Nama"),rs.getInt("Gaji"));
                listTabelPangkat.add(list);
            }
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
    }
        return listTabelPangkat;
    }
    public void showTabelPangkat(){
        ArrayList<listPangkat> list1= listTabelPangkat();
        DefaultTableModel  model = (DefaultTableModel)tabelPangkat.getModel();
        Object [] row = new Object[5];
        for(int i=0; i<list1.size();i++){
             row[0]=list1.get(i).getIDPangkat();
             row[1]=list1.get(i).getNamaPangkat();
             row[2]=list1.get(i).getIDKaryawan();
             row[3]=list1.get(i).getNama();
             row[4]=list1.get(i).getGaji();
             model.addRow(row);
        }
        
    }
    public ArrayList<listPangkat> listTabelPangkat1(){
        ArrayList<listPangkat> listTabelPangkat = new ArrayList<>();
       try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String tm=cariNama.getText();
            String query= "select Pangkat.IDPangkat, Pangkat.NamaKepangkatan, Karyawan.IDKaryawan, Karyawan.Nama, Pangkat.Gaji " +
                          "from Pangkat, Karyawan, Berpangkat " +
                          "where Pangkat.IDPangkat=Berpangkat.IDPangkat and Karyawan.IDKaryawan=Berpangkat.IDKaryawan and Nama like "+"'"+"%"+tm+"%"+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listPangkat list;
            while(rs.next()){
                list= new listPangkat(rs.getString("IDPangkat"),rs.getString("NamaKepangkatan"),
                                       rs.getString("IDKaryawan"),rs.getString("Nama"),rs.getInt("Gaji"));
                listTabelPangkat.add(list);
            }
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
    }
        return listTabelPangkat;
    }
    public void showTabelPangkat1(){
        ArrayList<listPangkat> list1= listTabelPangkat1();
        DefaultTableModel  model = (DefaultTableModel)tabelPangkat.getModel();
        Object [] row = new Object[5];
        for(int i=0; i<list1.size();i++){
             row[0]=list1.get(i).getIDPangkat();
             row[1]=list1.get(i).getNamaPangkat();
             row[2]=list1.get(i).getIDKaryawan();
             row[3]=list1.get(i).getNama();
             row[4]=list1.get(i).getGaji();
             model.addRow(row);
        }
        
    }
    public void sc(){
        DefaultTableModel  model = (DefaultTableModel)tabelPangkat.getModel();
        model.setRowCount(0);
        showTabelPangkat1();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPangkat = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cariNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPangkat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelPangkat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPangkat", "Pangkat", "IDKaryawan", "Nama Karyawan", "Gaji"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelPangkat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPangkatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPangkat);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 760, 200));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel1.setText("Pangkat");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("Cari Nama");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 70, 20));

        cariNama.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel2.add(cariNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 160, -1));

        jButton1.setBackground(new java.awt.Color(36, 47, 65));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        jButton2.setBackground(new java.awt.Color(36, 47, 65));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 340, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tabelPangkatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPangkatMouseClicked

    }//GEN-LAST:event_tabelPangkatMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sc();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel  model = (DefaultTableModel)tabelPangkat.getModel();
        model.setRowCount(0);
        showTabelPangkat();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariNama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPangkat;
    // End of variables declaration//GEN-END:variables
}
