
package sbd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import sbd.pro1;

/**
 *
 * @author shafira
 */
public class pro extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public pro() {
        initComponents();
        showTabel();
    }
    public ArrayList<listKeahlian> tabelProker (){
           ArrayList<listKeahlian> tabelProker = new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query= "select * from ProgramKerja";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listKeahlian list;
            while(rs.next()){
                list= new listKeahlian(rs.getString("IDProker"),rs.getString("NamaProker"),
                                       rs.getString("Keterangan"));
                tabelProker.add(list);
            }
         
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
        return tabelProker;
    }
    public void showTabel(){
        ArrayList<listKeahlian> list= tabelProker ();
        DefaultTableModel  model = (DefaultTableModel)tabelProker.getModel();
        Object [] row = new Object[3];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDKeahlian();
            row[1]=list.get(i).getNamaKeahlian();
            row[2]=list.get(i).getKeterangan();
            
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProker = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        editProker = new javax.swing.JTextField();
        editNamaProker = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        editKeterangan = new javax.swing.JTextField();
        inputproker = new javax.swing.JButton();
        deleteproker = new javax.swing.JButton();
        refreshproker = new javax.swing.JButton();
        editproker = new javax.swing.JButton();
        deleteproker1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setText("Program Kerja");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 210, -1));

        tabelProker.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelProker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Proker", "Nama Proker", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelProker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelProkerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelProker);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 680, 188));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("EDIT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("PR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Nama Proker");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        editProker.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editProker.setEnabled(false);
        jPanel1.add(editProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 90, -1));

        editNamaProker.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editNamaProker.setEnabled(false);
        jPanel1.add(editNamaProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 130, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Keterangan");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        editKeterangan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        editKeterangan.setEnabled(false);
        jPanel1.add(editKeterangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, -1));

        inputproker.setBackground(new java.awt.Color(36, 47, 65));
        inputproker.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        inputproker.setForeground(new java.awt.Color(255, 255, 255));
        inputproker.setText("INPUT");
        inputproker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputprokerMouseClicked(evt);
            }
        });
        inputproker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputprokerActionPerformed(evt);
            }
        });
        jPanel1.add(inputproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 70, 30));

        deleteproker.setBackground(new java.awt.Color(36, 47, 65));
        deleteproker.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        deleteproker.setForeground(new java.awt.Color(255, 255, 255));
        deleteproker.setText("UPDATE");
        deleteproker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteprokerActionPerformed(evt);
            }
        });
        jPanel1.add(deleteproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, 30));

        refreshproker.setBackground(new java.awt.Color(36, 47, 65));
        refreshproker.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        refreshproker.setForeground(new java.awt.Color(255, 255, 255));
        refreshproker.setText("REFRESH");
        refreshproker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshprokerActionPerformed(evt);
            }
        });
        jPanel1.add(refreshproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, 30));

        editproker.setBackground(new java.awt.Color(36, 47, 65));
        editproker.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        editproker.setForeground(new java.awt.Color(255, 255, 255));
        editproker.setText("EDIT");
        editproker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editprokerActionPerformed(evt);
            }
        });
        jPanel1.add(editproker, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 70, 30));

        deleteproker1.setBackground(new java.awt.Color(36, 47, 65));
        deleteproker1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        deleteproker1.setForeground(new java.awt.Color(255, 255, 255));
        deleteproker1.setText("DELETE");
        deleteproker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteproker1ActionPerformed(evt);
            }
        });
        jPanel1.add(deleteproker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("ID Proker");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputprokerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputprokerMouseClicked
        
    }//GEN-LAST:event_inputprokerMouseClicked

    private void inputprokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputprokerActionPerformed
         
pro1 select = new pro1();
select.setVisible(true);
                
    }//GEN-LAST:event_inputprokerActionPerformed

    private void refreshprokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshprokerActionPerformed
        DefaultTableModel  model = (DefaultTableModel)tabelProker.getModel();
        model.setRowCount(0);
        showTabel();
    }//GEN-LAST:event_refreshprokerActionPerformed

    private void editprokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editprokerActionPerformed
        editProker.setEnabled(true);
        editNamaProker.setEnabled(true);
        editKeterangan.setEnabled(true);
    }//GEN-LAST:event_editprokerActionPerformed

    private void tabelProkerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelProkerMouseClicked
        int angka = tabelProker.getSelectedRow();
        TableModel model = tabelProker.getModel();
        StringBuilder a= new StringBuilder(model.getValueAt(angka, 0).toString());
        editProker.setText(a.delete(0, 2).toString());
        editNamaProker.setText(model.getValueAt(angka, 1).toString());
        editKeterangan.setText(model.getValueAt(angka, 2).toString());
    }//GEN-LAST:event_tabelProkerMouseClicked

    private void deleteprokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteprokerActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            int row =tabelProker.getSelectedRow();
            String value= "'"+tabelProker.getModel().getValueAt(row, 0).toString()+"'";
//           
            String query2 = "update ProgramKerja set IDProker=?,NamaProker =? ,Keterangan=? where IDProker="
                    +value;
            
            PreparedStatement pst= con.prepareStatement(query2);
            pst.setString(1,"PR"+editProker.getText());
            pst.setString(2,editNamaProker.getText());
            pst.setString(3,editKeterangan.getText());
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated");
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
        
    
    }//GEN-LAST:event_deleteprokerActionPerformed

    private void deleteproker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteproker1ActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            int row =tabelProker.getSelectedRow();
            String value= ( tabelProker.getModel().getValueAt(row, 0).toString());
            String vl="'"+value+"'";
           
            
            String queryy="delete from ProgramKerja where IDProker="+vl;
            
            PreparedStatement pst= con.prepareStatement(queryy);
            
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "Delete Success");
            
            
            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    }//GEN-LAST:event_deleteproker1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteproker;
    private javax.swing.JButton deleteproker1;
    private javax.swing.JTextField editKeterangan;
    private javax.swing.JTextField editNamaProker;
    private javax.swing.JTextField editProker;
    private javax.swing.JButton editproker;
    private javax.swing.JButton inputproker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshproker;
    private javax.swing.JTable tabelProker;
    // End of variables declaration//GEN-END:variables
}
