/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sbd;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sbd.rencana1;
/**
 *
 * @author shafira
 */
public class rencana extends javax.swing.JPanel {

    /**
     * Creates new form home
     */
    public rencana() {
        initComponents();
        ComboProker();
        ComboDivisi();
        showTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelRencana = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        refreshRencana = new javax.swing.JButton();
        editRencana = new javax.swing.JButton();
        deleteRencana = new javax.swing.JButton();
        inputRencana = new javax.swing.JButton();
        editComboProker = new javax.swing.JComboBox<>();
        editComboDivisi = new javax.swing.JComboBox<>();
        updateRencana = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 30)); // NOI18N
        jLabel1.setText("Rencana");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 180, -1));

        tabelRencana.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        tabelRencana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Divisi", "NamaDivisi", "IDProker", "Nama Proker"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelRencana.setColumnSelectionAllowed(true);
        tabelRencana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRencanaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelRencana);
        tabelRencana.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 700, 188));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setText("EDIT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("ID Divisi");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("ID Proker");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        refreshRencana.setBackground(new java.awt.Color(36, 47, 65));
        refreshRencana.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        refreshRencana.setForeground(new java.awt.Color(255, 255, 255));
        refreshRencana.setText("REFRESH");
        refreshRencana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshRencanaActionPerformed(evt);
            }
        });
        jPanel1.add(refreshRencana, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, 90, 30));

        editRencana.setBackground(new java.awt.Color(36, 47, 65));
        editRencana.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        editRencana.setForeground(new java.awt.Color(255, 255, 255));
        editRencana.setText("EDIT");
        editRencana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRencanaActionPerformed(evt);
            }
        });
        jPanel1.add(editRencana, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 80, 30));

        deleteRencana.setBackground(new java.awt.Color(36, 47, 65));
        deleteRencana.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        deleteRencana.setForeground(new java.awt.Color(255, 255, 255));
        deleteRencana.setText("DELETE");
        deleteRencana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRencanaActionPerformed(evt);
            }
        });
        jPanel1.add(deleteRencana, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 80, 30));

        inputRencana.setBackground(new java.awt.Color(36, 47, 65));
        inputRencana.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        inputRencana.setForeground(new java.awt.Color(255, 255, 255));
        inputRencana.setText("INPUT");
        inputRencana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputRencanaActionPerformed(evt);
            }
        });
        jPanel1.add(inputRencana, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 90, 30));

        editComboProker.setEnabled(false);
        jPanel1.add(editComboProker, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 170, -1));

        editComboDivisi.setToolTipText("");
        editComboDivisi.setEnabled(false);
        jPanel1.add(editComboDivisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 170, -1));

        updateRencana.setBackground(new java.awt.Color(36, 47, 65));
        updateRencana.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        updateRencana.setForeground(new java.awt.Color(255, 255, 255));
        updateRencana.setText("UPDATE");
        updateRencana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRencanaActionPerformed(evt);
            }
        });
        jPanel1.add(updateRencana, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public ArrayList<listRencana> listTabelRencana (){
           ArrayList<listRencana> listTabelRencana= new ArrayList<>();
    
    try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            String query= "select Divisi.IDDivisi, Divisi.NamaDivisi, ProgramKerja.IDProker,ProgramKerja.NamaProker " +
                           " from Divisi, ProgramKerja, Rencana " +
                           " where Divisi.IDDivisi=Rencana.IDDivisi "
                        + "and ProgramKerja.IDProker=Rencana.IDProker";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            
            listRencana list;
            while(rs.next()){
                list = new listRencana(rs.getString("IDDivisi"),rs.getString("NamaDivisi"),rs.getString("IDProker"), rs.getString("NamaProker"));
                listTabelRencana.add(list);
            }
            
          
   }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    return listTabelRencana;
    }
    
    private void inputRencanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputRencanaActionPerformed
       rencana1 s = new rencana1();
       s.setVisible(true);
    }//GEN-LAST:event_inputRencanaActionPerformed
    public void showTabel(){
        ArrayList<listRencana> list= listTabelRencana ();
        DefaultTableModel  model = (DefaultTableModel)tabelRencana.getModel();
        Object [] row = new Object[4];
        for(int i=0; i<list.size();i++){
            row[0]=list.get(i).getIDDivisi();
            row[1]=list.get(i).getNamaDivisi();
            row[2]=list.get(i).getIDProker();
            row[3]=list.get(i).getNamaProker();
            
            model.addRow(row);
        }
    }
    private void refreshRencanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshRencanaActionPerformed
        DefaultTableModel  model = (DefaultTableModel)tabelRencana.getModel();
        model.setRowCount(0);
        showTabel();
    }//GEN-LAST:event_refreshRencanaActionPerformed
    private String ambilTabel(int row,int col){
        return tabelRencana.getModel().getValueAt(row, col).toString();
    }
    
    private void ComboProker(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query ="select * from ProgramKerja";
            PreparedStatement pst =con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("IDProker");
               // String name=rs.getString("NamaProker");
                editComboProker.addItem(id);
                
            }

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    
    
    
    
    private void ComboDivisi(){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            String query ="select * from Divisi";
            PreparedStatement pst =con.prepareStatement(query);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()){
                String id = rs.getString("IDDivisi");
                ///String name=rs.getString("NamaDivisi");
                editComboDivisi.addItem(id);
                
            }

            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
            
        }
    }
    private void tabelRencanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRencanaMouseClicked
        
        int angka = tabelRencana.getSelectedRow();
        
        for(int i=0; i<4; i++){
            if(i==0){
                editComboDivisi.setSelectedItem(ambilTabel(angka,i));
            }
            if(i==1){
                
            }
            if(i==2){
                editComboProker.setSelectedItem(ambilTabel(angka,i));
            }
            if(i==3){
                //editComboPangkat.setSelectedItem(ambilTabel(angka,i));
            }
        }
     
    }//GEN-LAST:event_tabelRencanaMouseClicked

    private void deleteRencanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRencanaActionPerformed
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            int row =tabelRencana.getSelectedRow();
            String value= ( tabelRencana.getModel().getValueAt(row, 0).toString());
            String vl="'"+value+"'";
            String NamaProker ="'"+tabelRencana.getModel().getValueAt(row, 2).toString()+"'";
            
            String queryy="delete from Rencana where IDDivisi="+vl+""
                    + " and "+"IDProker="+NamaProker;
            
            PreparedStatement pst= con.prepareStatement(queryy);
            
            pst.executeUpdate();
           
            JOptionPane.showMessageDialog(null, "Delete Success");
            
            
            
            }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    }//GEN-LAST:event_deleteRencanaActionPerformed

    private void editRencanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRencanaActionPerformed
        editComboDivisi.setEnabled(true);
        editComboProker.setEnabled(true);
        //editTanggalJabat.setEnabled(true);
    }//GEN-LAST:event_editRencanaActionPerformed

    private void updateRencanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRencanaActionPerformed
        try{
            
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://localhost:1433;databaseName=ProjectEASsbd;user=firman;password=s1910";
            Connection con = DriverManager.getConnection(url);
            
            int row =tabelRencana.getSelectedRow();
            String a= "'"+tabelRencana.getModel().getValueAt(row, 0).toString()+"'";
            String b ="'"+tabelRencana.getModel().getValueAt(row, 2).toString()+"'";
            String query2 = "update Rencana " +
                            "set IDDivisi= ?, IDProker=?" +
                            " where IDDivisi="+a+" and "+ "IDProker=" +b;
            
            PreparedStatement pst= con.prepareStatement(query2);
            pst.setString(1,editComboDivisi.getSelectedItem().toString());
            pst.setString(2,editComboProker.getSelectedItem().toString());
//            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated");
            
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        
    }
    }//GEN-LAST:event_updateRencanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteRencana;
    private javax.swing.JComboBox<String> editComboDivisi;
    private javax.swing.JComboBox<String> editComboProker;
    private javax.swing.JButton editRencana;
    private javax.swing.JButton inputRencana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshRencana;
    private javax.swing.JTable tabelRencana;
    private javax.swing.JButton updateRencana;
    // End of variables declaration//GEN-END:variables
}
